version: "3"

services:
    web:
        container_name: ec_web_client
        build:
            context: ./web
            dockerfile: dockerfile.production
        stdin_open: true
        volumes:
            - ./web:/usr/src/web
            - ./web/node_modules:/usr/src/web/node_modules
        environment: 
            - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - REACT_APP_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
            - REACT_APP_URI=${DEV_URI}
        ports:
            - "3000"
    auth:
        container_name: ec_auth_service
        build: 
            context: ./auth
            dockerfile: dockerfile.production
        ports: 
            - "5000"
        volumes: 
            - ./auth:/usr/src/auth
        environment: 
            - DATABASE_HOST=${DB_HOST}
            - DATABASE_NAME=${DB_NAME}
            - TEST_DATABASE_NAME=tests
            - DATABASE_PORT=${DB_PORT}
            - DATABASE_USER=${DB_USER}
            - DATABASE_PASSWORD=${DB_PASSWORD}
            - EMAIL_PWD=${EMAIL_PWD}
            - URI={$DEV_URI}
            - PORT=5000
    products:
        container_name: ec_products_service
        build:
            context: ./products
            dockerfile: dockerfile.production
        volumes: 
                - ./products:/usr/src/api/products
                - ./products/node_modules:/usr/src/api/products/node_modules
        ports:
            - "5000"
        command: >
            sh -c "npm run dev"
        environment:
            - DB_URI:${MONGO_DB_URI}
            - PORT:5000
    nginx:
        container_name: ec_nginx_proxy
        build:
            context: .
            dockerfile: dockerfile.production
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        environment: 
            - PORT:80
        depends_on:
            - web
            - auth
            - products
